#!/usr/bin/env python3
# -*- encoding: utf-8 -*-
'''
@文件    :metric_db2.py
@说明    :DB2 运行信息采集
@时间    :2024/05/14 11:13:42
@作者    :xxxx
@版本    :2.0.1
'''

import sys
from datetime import datetime

sys.path.append('/usr/software/knowl')
import json
import DBUtil


def cs(val, dt=False):
    if val is None:
        return ''
    else:
        if dt:
            return val.strftime('%Y-%m-%d %H:%M:%S')
        else:
            if isinstance(val, list):
                return val
            else:
                return str(val)


def get_db2_health(db2, metric):
    "获取DB2运行信息"
    # 获取时间戳
    sql = """SELECT TIMESTAMPDIFF(2, CHAR(CURRENT_TIMESTAMP - TIMESTAMP('1970-01-01-00.00.00'))) + 0 as "time" FROM SYSIBM.SYSDUMMY1;"""
    rs = DBUtil.getValue(db2, sql)
    metric.append(dict(index_id="2500001", value=cs(rs[0]['time'])))
    # 获取DB2运行信息
    sql2 = "SELECT * from table(MON_GET_DATABASE(-2))"
    rs2 = DBUtil.getValue(db2, sql2)
    cur_conns = 0
    for row in rs2:
        cur_conns = row['APPLS_IN_DB2']
        metric.append(dict(index_id="2500002", value=cs(row['MEMBER'])))
        metric.append(dict(index_id="2500004", value=cs(row['DB_STATUS'])))
        metric.append(dict(index_id="2500006", value=cs(row['DB_ACTIVATION_STATE'])))
        metric.append(dict(index_id="2500008", value=cs(row['DB_CONN_TIME'])))
        metric.append(dict(index_id="2500010", value=cs(row['CATALOG_PARTITION'])))
        metric.append(dict(index_id="2500012", value=cs(row['LAST_BACKUP'])))
        metric.append(dict(index_id="2500014", value=cs(row['CONNECTIONS_TOP'])))
        metric.append(dict(index_id="2500016", value=cs(row['TOTAL_CONS'])))
        metric.append(dict(index_id="2500018", value=cs(row['TOTAL_SEC_CONS'])))
        metric.append(dict(index_id="2500020", value=cs(row['APPLS_CUR_CONS'])))
        metric.append(dict(index_id="2500022", value=cs(row['APPLS_IN_DB2'])))
        metric.append(dict(index_id="2500024", value=cs(row['NUM_ASSOC_AGENTS'])))
        metric.append(dict(index_id="2500026", value=cs(row['AGENTS_TOP'])))
        metric.append(dict(index_id="2500028", value=cs(row['NUM_COORD_AGENTS'])))
        metric.append(dict(index_id="2500030", value=cs(row['COORD_AGENTS_TOP'])))
        metric.append(dict(index_id="2500032", value=cs(row['NUM_LOCKS_HELD'])))
        metric.append(dict(index_id="2500034", value=cs(row['NUM_LOCKS_WAITING'])))
        metric.append(dict(index_id="2500036", value=cs(row['LOCK_LIST_IN_USE'])))
        metric.append(dict(index_id="2500038", value=cs(row['ACTIVE_SORTS'])))
        metric.append(dict(index_id="2500040", value=cs(row['ACTIVE_HASH_JOINS'])))
        metric.append(dict(index_id="2500042", value=cs(row['ACTIVE_OLAP_FUNCS'])))
        metric.append(dict(index_id="2500044", value=cs(row['DB_PATH'])))
        metric.append(dict(index_id="2500046", value=cs(row['ACT_ABORTED_TOTAL'])))
        metric.append(dict(index_id="2500048", value=cs(row['ACT_COMPLETED_TOTAL'])))
        metric.append(dict(index_id="2500050", value=cs(row['ACT_REJECTED_TOTAL'])))
        metric.append(dict(index_id="2500052", value=cs(row['AGENT_WAIT_TIME'])))
        metric.append(dict(index_id="2500054", value=cs(row['AGENT_WAITS_TOTAL'])))
        metric.append(dict(index_id="2500056", value=cs(row['POOL_DATA_L_READS'])))
        metric.append(dict(index_id="2500058", value=cs(row['POOL_INDEX_L_READS'])))
        metric.append(dict(index_id="2500060", value=cs(row['POOL_TEMP_DATA_L_READS'])))
        metric.append(dict(index_id="2500062", value=cs(row['POOL_TEMP_INDEX_L_READS'])))
        metric.append(dict(index_id="2500064", value=cs(row['POOL_TEMP_XDA_L_READS'])))
        metric.append(dict(index_id="2500066", value=cs(row['POOL_XDA_L_READS'])))
        metric.append(dict(index_id="2500068", value=cs(row['POOL_DATA_P_READS'])))
        metric.append(dict(index_id="2500070", value=cs(row['POOL_INDEX_P_READS'])))
        metric.append(dict(index_id="2500072", value=cs(row['POOL_TEMP_DATA_P_READS'])))
        metric.append(dict(index_id="2500074", value=cs(row['POOL_TEMP_INDEX_P_READS'])))
        metric.append(dict(index_id="2500076", value=cs(row['POOL_TEMP_XDA_P_READS'])))
        metric.append(dict(index_id="2500078", value=cs(row['POOL_XDA_P_READS'])))
        metric.append(dict(index_id="2500080", value=cs(row['POOL_DATA_WRITES'])))
        metric.append(dict(index_id="2500082", value=cs(row['POOL_INDEX_WRITES'])))
        metric.append(dict(index_id="2500084", value=cs(row['POOL_XDA_WRITES'])))
        metric.append(dict(index_id="2500086", value=cs(row['POOL_READ_TIME'])))
        metric.append(dict(index_id="2500088", value=cs(row['POOL_WRITE_TIME'])))
        metric.append(dict(index_id="2500090", value=cs(row['CLIENT_IDLE_WAIT_TIME'])))
        metric.append(dict(index_id="2500092", value=cs(row['DEADLOCKS'])))
        metric.append(dict(index_id="2500094", value=cs(row['DIRECT_READS'])))
        metric.append(dict(index_id="2500096", value=cs(row['DIRECT_READ_TIME'])))
        metric.append(dict(index_id="2500098", value=cs(row['DIRECT_WRITES'])))
        metric.append(dict(index_id="2500100", value=cs(row['DIRECT_WRITE_TIME'])))
        metric.append(dict(index_id="2500102", value=cs(row['DIRECT_READ_REQS'])))
        metric.append(dict(index_id="2500104", value=cs(row['DIRECT_WRITE_REQS'])))
        metric.append(dict(index_id="2500106", value=cs(row['FCM_RECV_VOLUME'])))
        metric.append(dict(index_id="2500108", value=cs(row['FCM_RECVS_TOTAL'])))
        metric.append(dict(index_id="2500110", value=cs(row['FCM_SEND_VOLUME'])))
        metric.append(dict(index_id="2500112", value=cs(row['FCM_SENDS_TOTAL'])))
        metric.append(dict(index_id="2500114", value=cs(row['FCM_RECV_WAIT_TIME'])))
        metric.append(dict(index_id="2500116", value=cs(row['FCM_SEND_WAIT_TIME'])))
        metric.append(dict(index_id="2500118", value=cs(row['IPC_RECV_VOLUME'])))
        metric.append(dict(index_id="2500120", value=cs(row['IPC_RECV_WAIT_TIME'])))
        metric.append(dict(index_id="2500122", value=cs(row['IPC_RECVS_TOTAL'])))
        metric.append(dict(index_id="2500124", value=cs(row['IPC_SEND_VOLUME'])))
        metric.append(dict(index_id="2500126", value=cs(row['IPC_SEND_WAIT_TIME'])))
        metric.append(dict(index_id="2500128", value=cs(row['IPC_SENDS_TOTAL'])))
        metric.append(dict(index_id="2500130", value=cs(row['LOCK_ESCALS'])))
        metric.append(dict(index_id="2500132", value=cs(row['LOCK_TIMEOUTS'])))
        metric.append(dict(index_id="2500134", value=cs(row['LOCK_WAIT_TIME'])))
        metric.append(dict(index_id="2500136", value=cs(row['LOCK_WAITS'])))
        metric.append(dict(index_id="2500138", value=cs(row['LOG_BUFFER_WAIT_TIME'])))
        metric.append(dict(index_id="2500140", value=cs(row['NUM_LOG_BUFFER_FULL'])))
        metric.append(dict(index_id="2500142", value=cs(row['LOG_DISK_WAIT_TIME'])))
        metric.append(dict(index_id="2500144", value=cs(row['LOG_DISK_WAITS_TOTAL'])))
        metric.append(dict(index_id="2500146", value=cs(row['RQSTS_COMPLETED_TOTAL'])))
        metric.append(dict(index_id="2500148", value=cs(row['ROWS_MODIFIED'])))
        metric.append(dict(index_id="2500150", value=cs(row['ROWS_READ'])))
        metric.append(dict(index_id="2500152", value=cs(row['ROWS_RETURNED'])))
        metric.append(dict(index_id="2500154", value=cs(row['TCPIP_RECV_VOLUME'])))
        metric.append(dict(index_id="2500156", value=cs(row['TCPIP_SEND_VOLUME'])))
        metric.append(dict(index_id="2500158", value=cs(row['TCPIP_RECV_WAIT_TIME'])))
        metric.append(dict(index_id="2500160", value=cs(row['TCPIP_RECVS_TOTAL'])))
        metric.append(dict(index_id="2500162", value=cs(row['TCPIP_SEND_WAIT_TIME'])))
        metric.append(dict(index_id="2500164", value=cs(row['TCPIP_SENDS_TOTAL'])))
        metric.append(dict(index_id="2500166", value=cs(row['TOTAL_APP_RQST_TIME'])))
        metric.append(dict(index_id="2500168", value=cs(row['TOTAL_RQST_TIME'])))
        metric.append(dict(index_id="2500170", value=cs(row['WLM_QUEUE_TIME_TOTAL'])))
        metric.append(dict(index_id="2500172", value=cs(row['WLM_QUEUE_ASSIGNMENTS_TOTAL'])))
        metric.append(dict(index_id="2500174", value=cs(row['TOTAL_RQST_MAPPED_IN'])))
        metric.append(dict(index_id="2500176", value=cs(row['TOTAL_RQST_MAPPED_OUT'])))
        metric.append(dict(index_id="2500178", value=cs(row['TOTAL_CPU_TIME'])))
        metric.append(dict(index_id="2500180", value=cs(row['TOTAL_WAIT_TIME'])))
        metric.append(dict(index_id="2500182", value=cs(row['APP_RQSTS_COMPLETED_TOTAL'])))
        metric.append(dict(index_id="2500184", value=cs(row['TOTAL_SECTION_SORT_TIME'])))
        metric.append(dict(index_id="2500186", value=cs(row['TOTAL_SECTION_SORT_PROC_TIME'])))
        metric.append(dict(index_id="2500188", value=cs(row['TOTAL_SECTION_SORTS'])))
        metric.append(dict(index_id="2500190", value=cs(row['TOTAL_SORTS'])))
        metric.append(dict(index_id="2500192", value=cs(row['POST_THRESHOLD_SORTS'])))
        metric.append(dict(index_id="2500194", value=cs(row['POST_SHRTHRESHOLD_SORTS'])))
        metric.append(dict(index_id="2500196", value=cs(row['SORT_OVERFLOWS'])))
        metric.append(dict(index_id="2500198", value=cs(row['TOTAL_COMPILE_TIME'])))
        metric.append(dict(index_id="2500200", value=cs(row['TOTAL_COMPILE_PROC_TIME'])))
        metric.append(dict(index_id="2500202", value=cs(row['TOTAL_COMPILATIONS'])))
        metric.append(dict(index_id="2500204", value=cs(row['TOTAL_IMPLICIT_COMPILE_TIME'])))
        metric.append(dict(index_id="2500206", value=cs(row['TOTAL_IMPLICIT_COMPILE_PROC_TIME'])))
        metric.append(dict(index_id="2500208", value=cs(row['TOTAL_IMPLICIT_COMPILATIONS'])))
        metric.append(dict(index_id="2500210", value=cs(row['TOTAL_SECTION_TIME'])))
        metric.append(dict(index_id="2500212", value=cs(row['TOTAL_SECTION_PROC_TIME'])))
        metric.append(dict(index_id="2500214", value=cs(row['TOTAL_APP_SECTION_EXECUTIONS'])))
        metric.append(dict(index_id="2500216", value=cs(row['TOTAL_ACT_TIME'])))
        metric.append(dict(index_id="2500218", value=cs(row['TOTAL_ACT_WAIT_TIME'])))
        metric.append(dict(index_id="2500220", value=cs(row['ACT_RQSTS_TOTAL'])))
        metric.append(dict(index_id="2500222", value=cs(row['TOTAL_ROUTINE_TIME'])))
        metric.append(dict(index_id="2500224", value=cs(row['TOTAL_ROUTINE_INVOCATIONS'])))
        metric.append(dict(index_id="2500226", value=cs(row['TOTAL_COMMIT_TIME'])))
        metric.append(dict(index_id="2500228", value=cs(row['TOTAL_COMMIT_PROC_TIME'])))
        metric.append(dict(index_id="2500230", value=cs(row['TOTAL_APP_COMMITS'])))
        metric.append(dict(index_id="2500232", value=cs(row['INT_COMMITS'])))
        metric.append(dict(index_id="2500234", value=cs(row['TOTAL_ROLLBACK_TIME'])))
        metric.append(dict(index_id="2500236", value=cs(row['TOTAL_ROLLBACK_PROC_TIME'])))
        metric.append(dict(index_id="2500238", value=cs(row['TOTAL_APP_ROLLBACKS'])))
        metric.append(dict(index_id="2500240", value=cs(row['INT_ROLLBACKS'])))
        metric.append(dict(index_id="2500242", value=cs(row['TOTAL_RUNSTATS_TIME'])))
        metric.append(dict(index_id="2500244", value=cs(row['TOTAL_RUNSTATS_PROC_TIME'])))
        metric.append(dict(index_id="2500246", value=cs(row['TOTAL_RUNSTATS'])))
        metric.append(dict(index_id="2500248", value=cs(row['TOTAL_REORG_TIME'])))
        metric.append(dict(index_id="2500250", value=cs(row['TOTAL_REORG_PROC_TIME'])))
        metric.append(dict(index_id="2500252", value=cs(row['TOTAL_REORGS'])))
        metric.append(dict(index_id="2500254", value=cs(row['TOTAL_LOAD_TIME'])))
        metric.append(dict(index_id="2500256", value=cs(row['TOTAL_LOAD_PROC_TIME'])))
        metric.append(dict(index_id="2500258", value=cs(row['TOTAL_LOADS'])))
        metric.append(dict(index_id="2500260", value=cs(row['CAT_CACHE_INSERTS'])))
        metric.append(dict(index_id="2500262", value=cs(row['CAT_CACHE_LOOKUPS'])))
        metric.append(dict(index_id="2500264", value=cs(row['PKG_CACHE_INSERTS'])))
        metric.append(dict(index_id="2500266", value=cs(row['PKG_CACHE_LOOKUPS'])))
        metric.append(dict(index_id="2500268", value=cs(row['THRESH_VIOLATIONS'])))
        metric.append(dict(index_id="2500270", value=cs(row['NUM_LW_THRESH_EXCEEDED'])))
        metric.append(dict(index_id="2500272", value=cs(row['LOCK_WAITS_GLOBAL'])))
        metric.append(dict(index_id="2500274", value=cs(row['LOCK_WAIT_TIME_GLOBAL'])))
        metric.append(dict(index_id="2500276", value=cs(row['LOCK_TIMEOUTS_GLOBAL'])))
        metric.append(dict(index_id="2500278", value=cs(row['LOCK_ESCALS_MAXLOCKS'])))
        metric.append(dict(index_id="2500280", value=cs(row['LOCK_ESCALS_LOCKLIST'])))
        metric.append(dict(index_id="2500282", value=cs(row['LOCK_ESCALS_GLOBAL'])))
        metric.append(dict(index_id="2500284", value=cs(row['DATA_SHARING_REMOTE_LOCKWAIT_COUNT'])))
        metric.append(dict(index_id="2500286", value=cs(row['DATA_SHARING_REMOTE_LOCKWAIT_TIME'])))
        metric.append(dict(index_id="2500288", value=cs(row['RECLAIM_WAIT_TIME'])))
        metric.append(dict(index_id="2500290", value=cs(row['SPACEMAPPAGE_RECLAIM_WAIT_TIME'])))
        metric.append(dict(index_id="2500292", value=cs(row['CF_WAITS'])))
        metric.append(dict(index_id="2500294", value=cs(row['CF_WAIT_TIME'])))
        metric.append(dict(index_id="2500296", value=cs(row['POOL_DATA_GBP_L_READS'])))
        metric.append(dict(index_id="2500298", value=cs(row['POOL_DATA_GBP_P_READS'])))
        metric.append(dict(index_id="2500300", value=cs(row['POOL_DATA_LBP_PAGES_FOUND'])))
        metric.append(dict(index_id="2500302", value=cs(row['POOL_DATA_GBP_INVALID_PAGES'])))
        metric.append(dict(index_id="2500304", value=cs(row['POOL_INDEX_GBP_L_READS'])))
        metric.append(dict(index_id="2500306", value=cs(row['POOL_INDEX_GBP_P_READS'])))
        metric.append(dict(index_id="2500308", value=cs(row['POOL_INDEX_LBP_PAGES_FOUND'])))
        metric.append(dict(index_id="2500310", value=cs(row['POOL_INDEX_GBP_INVALID_PAGES'])))
        metric.append(dict(index_id="2500312", value=cs(row['POOL_XDA_GBP_L_READS'])))
        metric.append(dict(index_id="2500314", value=cs(row['POOL_XDA_GBP_P_READS'])))
        metric.append(dict(index_id="2500316", value=cs(row['POOL_XDA_LBP_PAGES_FOUND'])))
        metric.append(dict(index_id="2500318", value=cs(row['POOL_XDA_GBP_INVALID_PAGES'])))
        metric.append(dict(index_id="2500320", value=cs(row['AUDIT_EVENTS_TOTAL'])))
        metric.append(dict(index_id="2500322", value=cs(row['AUDIT_FILE_WRITES_TOTAL'])))
        metric.append(dict(index_id="2500324", value=cs(row['AUDIT_FILE_WRITE_WAIT_TIME'])))
        metric.append(dict(index_id="2500326", value=cs(row['AUDIT_SUBSYSTEM_WAITS_TOTAL'])))
        metric.append(dict(index_id="2500328", value=cs(row['AUDIT_SUBSYSTEM_WAIT_TIME'])))
        metric.append(dict(index_id="2500330", value=cs(row['DIAGLOG_WRITES_TOTAL'])))
        metric.append(dict(index_id="2500332", value=cs(row['DIAGLOG_WRITE_WAIT_TIME'])))
        metric.append(dict(index_id="2500334", value=cs(row['FCM_MESSAGE_RECVS_TOTAL'])))
        metric.append(dict(index_id="2500336", value=cs(row['FCM_MESSAGE_RECV_VOLUME'])))
        metric.append(dict(index_id="2500338", value=cs(row['FCM_MESSAGE_RECV_WAIT_TIME'])))
        metric.append(dict(index_id="2500340", value=cs(row['FCM_MESSAGE_SENDS_TOTAL'])))
        metric.append(dict(index_id="2500342", value=cs(row['FCM_MESSAGE_SEND_VOLUME'])))
        metric.append(dict(index_id="2500344", value=cs(row['FCM_MESSAGE_SEND_WAIT_TIME'])))
        metric.append(dict(index_id="2500346", value=cs(row['FCM_TQ_RECVS_TOTAL'])))
        metric.append(dict(index_id="2500348", value=cs(row['FCM_TQ_RECV_VOLUME'])))
        metric.append(dict(index_id="2500350", value=cs(row['FCM_TQ_RECV_WAIT_TIME'])))
        metric.append(dict(index_id="2500352", value=cs(row['FCM_TQ_SENDS_TOTAL'])))
        metric.append(dict(index_id="2500354", value=cs(row['FCM_TQ_SEND_VOLUME'])))
        metric.append(dict(index_id="2500356", value=cs(row['FCM_TQ_SEND_WAIT_TIME'])))
        metric.append(dict(index_id="2500358", value=cs(row['TOTAL_ROUTINE_USER_CODE_PROC_TIME'])))
        metric.append(dict(index_id="2500360", value=cs(row['TOTAL_ROUTINE_USER_CODE_TIME'])))
        metric.append(dict(index_id="2500362", value=cs(row['TQ_TOT_SEND_SPILLS'])))
        metric.append(dict(index_id="2500364", value=cs(row['EVMON_WAIT_TIME'])))
        metric.append(dict(index_id="2500366", value=cs(row['EVMON_WAITS_TOTAL'])))
        metric.append(dict(index_id="2500368", value=cs(row['TOTAL_EXTENDED_LATCH_WAIT_TIME'])))
        metric.append(dict(index_id="2500370", value=cs(row['TOTAL_EXTENDED_LATCH_WAITS'])))
        metric.append(dict(index_id="2500372", value=cs(row['TOTAL_STATS_FABRICATION_TIME'])))
        metric.append(dict(index_id="2500374", value=cs(row['TOTAL_STATS_FABRICATION_PROC_TIME'])))
        metric.append(dict(index_id="2500376", value=cs(row['TOTAL_STATS_FABRICATIONS'])))
        metric.append(dict(index_id="2500378", value=cs(row['TOTAL_SYNC_RUNSTATS_TIME'])))
        metric.append(dict(index_id="2500380", value=cs(row['TOTAL_SYNC_RUNSTATS_PROC_TIME'])))
        metric.append(dict(index_id="2500382", value=cs(row['TOTAL_SYNC_RUNSTATS'])))
        metric.append(dict(index_id="2500384", value=cs(row['TOTAL_DISP_RUN_QUEUE_TIME'])))
        metric.append(dict(index_id="2500386", value=cs(row['TOTAL_PEDS'])))
        metric.append(dict(index_id="2500388", value=cs(row['DISABLED_PEDS'])))
        metric.append(dict(index_id="2500390", value=cs(row['POST_THRESHOLD_PEDS'])))
        metric.append(dict(index_id="2500392", value=cs(row['TOTAL_PEAS'])))
        metric.append(dict(index_id="2500394", value=cs(row['POST_THRESHOLD_PEAS'])))
        metric.append(dict(index_id="2500396", value=cs(row['TQ_SORT_HEAP_REQUESTS'])))
        metric.append(dict(index_id="2500398", value=cs(row['TQ_SORT_HEAP_REJECTIONS'])))
        metric.append(dict(index_id="2500400", value=cs(row['POOL_QUEUED_ASYNC_DATA_REQS'])))
        metric.append(dict(index_id="2500402", value=cs(row['POOL_QUEUED_ASYNC_INDEX_REQS'])))
        metric.append(dict(index_id="2500404", value=cs(row['POOL_QUEUED_ASYNC_XDA_REQS'])))
        metric.append(dict(index_id="2500406", value=cs(row['POOL_QUEUED_ASYNC_TEMP_DATA_REQS'])))
        metric.append(dict(index_id="2500408", value=cs(row['POOL_QUEUED_ASYNC_TEMP_INDEX_REQS'])))
        metric.append(dict(index_id="2500410", value=cs(row['POOL_QUEUED_ASYNC_TEMP_XDA_REQS'])))
        metric.append(dict(index_id="2500412", value=cs(row['POOL_QUEUED_ASYNC_OTHER_REQS'])))
        metric.append(dict(index_id="2500414", value=cs(row['POOL_QUEUED_ASYNC_DATA_PAGES'])))
        metric.append(dict(index_id="2500416", value=cs(row['POOL_QUEUED_ASYNC_INDEX_PAGES'])))
        metric.append(dict(index_id="2500418", value=cs(row['POOL_QUEUED_ASYNC_XDA_PAGES'])))
        metric.append(dict(index_id="2500420", value=cs(row['POOL_QUEUED_ASYNC_TEMP_DATA_PAGES'])))
        metric.append(dict(index_id="2500422", value=cs(row['POOL_QUEUED_ASYNC_TEMP_INDEX_PAGES'])))
        metric.append(dict(index_id="2500424", value=cs(row['POOL_QUEUED_ASYNC_TEMP_XDA_PAGES'])))
        metric.append(dict(index_id="2500426", value=cs(row['POOL_FAILED_ASYNC_DATA_REQS'])))
        metric.append(dict(index_id="2500428", value=cs(row['POOL_FAILED_ASYNC_INDEX_REQS'])))
        metric.append(dict(index_id="2500430", value=cs(row['POOL_FAILED_ASYNC_XDA_REQS'])))
        metric.append(dict(index_id="2500432", value=cs(row['POOL_FAILED_ASYNC_TEMP_DATA_REQS'])))
        metric.append(dict(index_id="2500434", value=cs(row['POOL_FAILED_ASYNC_TEMP_INDEX_REQS'])))
        metric.append(dict(index_id="2500436", value=cs(row['POOL_FAILED_ASYNC_TEMP_XDA_REQS'])))
        metric.append(dict(index_id="2500438", value=cs(row['POOL_FAILED_ASYNC_OTHER_REQS'])))
        metric.append(dict(index_id="2500440", value=cs(row['PREFETCH_WAIT_TIME'])))
        metric.append(dict(index_id="2500442", value=cs(row['PREFETCH_WAITS'])))
        metric.append(dict(index_id="2500444", value=cs(row['APP_ACT_COMPLETED_TOTAL'])))
        metric.append(dict(index_id="2500446", value=cs(row['APP_ACT_ABORTED_TOTAL'])))
        metric.append(dict(index_id="2500448", value=cs(row['APP_ACT_REJECTED_TOTAL'])))
        metric.append(dict(index_id="2500450", value=cs(row['TOTAL_CONNECT_REQUEST_TIME'])))
        metric.append(dict(index_id="2500452", value=cs(row['TOTAL_CONNECT_REQUEST_PROC_TIME'])))
        metric.append(dict(index_id="2500454", value=cs(row['TOTAL_CONNECT_REQUESTS'])))
        metric.append(dict(index_id="2500456", value=cs(row['TOTAL_CONNECT_AUTHENTICATION_TIME'])))
        metric.append(dict(index_id="2500458", value=cs(row['TOTAL_CONNECT_AUTHENTICATION_PROC_TIME'])))
        metric.append(dict(index_id="2500460", value=cs(row['TOTAL_CONNECT_AUTHENTICATIONS'])))
        metric.append(dict(index_id="2500462", value=cs(row['POOL_DATA_GBP_INDEP_PAGES_FOUND_IN_LBP'])))
        metric.append(dict(index_id="2500464", value=cs(row['POOL_INDEX_GBP_INDEP_PAGES_FOUND_IN_LBP'])))
        metric.append(dict(index_id="2500466", value=cs(row['POOL_XDA_GBP_INDEP_PAGES_FOUND_IN_LBP'])))
        metric.append(dict(index_id="2500468", value=cs(row['COMM_EXIT_WAIT_TIME'])))
        metric.append(dict(index_id="2500470", value=cs(row['COMM_EXIT_WAITS'])))
        metric.append(dict(index_id="2500472", value=cs(row['POOL_ASYNC_DATA_READS'])))
        metric.append(dict(index_id="2500474", value=cs(row['POOL_ASYNC_DATA_READ_REQS'])))
        metric.append(dict(index_id="2500476", value=cs(row['POOL_ASYNC_DATA_WRITES'])))
        metric.append(dict(index_id="2500478", value=cs(row['POOL_ASYNC_INDEX_READS'])))
        metric.append(dict(index_id="2500480", value=cs(row['POOL_ASYNC_INDEX_READ_REQS'])))
        metric.append(dict(index_id="2500482", value=cs(row['POOL_ASYNC_INDEX_WRITES'])))
        metric.append(dict(index_id="2500484", value=cs(row['POOL_ASYNC_XDA_READS'])))
        metric.append(dict(index_id="2500486", value=cs(row['POOL_ASYNC_XDA_READ_REQS'])))
        metric.append(dict(index_id="2500488", value=cs(row['POOL_ASYNC_XDA_WRITES'])))
        metric.append(dict(index_id="2500490", value=cs(row['POOL_NO_VICTIM_BUFFER'])))
        metric.append(dict(index_id="2500492", value=cs(row['POOL_LSN_GAP_CLNS'])))
        metric.append(dict(index_id="2500494", value=cs(row['POOL_DRTY_PG_STEAL_CLNS'])))
        metric.append(dict(index_id="2500496", value=cs(row['POOL_DRTY_PG_THRSH_CLNS'])))
        metric.append(dict(index_id="2500498", value=cs(row['VECTORED_IOS'])))
        metric.append(dict(index_id="2500500", value=cs(row['PAGES_FROM_VECTORED_IOS'])))
        metric.append(dict(index_id="2500502", value=cs(row['BLOCK_IOS'])))
        metric.append(dict(index_id="2500504", value=cs(row['PAGES_FROM_BLOCK_IOS'])))
        metric.append(dict(index_id="2500506", value=cs(row['UNREAD_PREFETCH_PAGES'])))
        metric.append(dict(index_id="2500508", value=cs(row['FILES_CLOSED'])))
        metric.append(dict(index_id="2500510", value=cs(row['POOL_ASYNC_DATA_GBP_L_READS'])))
        metric.append(dict(index_id="2500512", value=cs(row['POOL_ASYNC_DATA_GBP_P_READS'])))
        metric.append(dict(index_id="2500514", value=cs(row['POOL_ASYNC_DATA_LBP_PAGES_FOUND'])))
        metric.append(dict(index_id="2500516", value=cs(row['POOL_ASYNC_DATA_GBP_INVALID_PAGES'])))
        metric.append(dict(index_id="2500518", value=cs(row['POOL_ASYNC_INDEX_GBP_L_READS'])))
        metric.append(dict(index_id="2500520", value=cs(row['POOL_ASYNC_INDEX_GBP_P_READS'])))
        metric.append(dict(index_id="2500522", value=cs(row['POOL_ASYNC_INDEX_LBP_PAGES_FOUND'])))
        metric.append(dict(index_id="2500524", value=cs(row['POOL_ASYNC_INDEX_GBP_INVALID_PAGES'])))
        metric.append(dict(index_id="2500526", value=cs(row['POOL_ASYNC_XDA_GBP_L_READS'])))
        metric.append(dict(index_id="2500528", value=cs(row['POOL_ASYNC_XDA_GBP_P_READS'])))
        metric.append(dict(index_id="2500530", value=cs(row['POOL_ASYNC_XDA_LBP_PAGES_FOUND'])))
        metric.append(dict(index_id="2500532", value=cs(row['POOL_ASYNC_XDA_GBP_INVALID_PAGES'])))
        metric.append(dict(index_id="2500534", value=cs(row['POOL_ASYNC_READ_TIME'])))
        metric.append(dict(index_id="2500536", value=cs(row['POOL_ASYNC_WRITE_TIME'])))
        metric.append(dict(index_id="2500538", value=cs(row['SKIPPED_PREFETCH_DATA_P_READS'])))
        metric.append(dict(index_id="2500540", value=cs(row['SKIPPED_PREFETCH_INDEX_P_READS'])))
        metric.append(dict(index_id="2500542", value=cs(row['SKIPPED_PREFETCH_XDA_P_READS'])))
        metric.append(dict(index_id="2500544", value=cs(row['SKIPPED_PREFETCH_TEMP_DATA_P_READS'])))
        metric.append(dict(index_id="2500546", value=cs(row['SKIPPED_PREFETCH_TEMP_INDEX_P_READS'])))
        metric.append(dict(index_id="2500548", value=cs(row['SKIPPED_PREFETCH_TEMP_XDA_P_READS'])))
        metric.append(dict(index_id="2500550", value=cs(row['SKIPPED_PREFETCH_UOW_DATA_P_READS'])))
        metric.append(dict(index_id="2500552", value=cs(row['SKIPPED_PREFETCH_UOW_INDEX_P_READS'])))
        metric.append(dict(index_id="2500554", value=cs(row['SKIPPED_PREFETCH_UOW_XDA_P_READS'])))
        metric.append(dict(index_id="2500556", value=cs(row['SKIPPED_PREFETCH_UOW_TEMP_DATA_P_READS'])))
        metric.append(dict(index_id="2500558", value=cs(row['SKIPPED_PREFETCH_UOW_TEMP_INDEX_P_READS'])))
        metric.append(dict(index_id="2500560", value=cs(row['SKIPPED_PREFETCH_UOW_TEMP_XDA_P_READS'])))
        metric.append(dict(index_id="2500562", value=cs(row['POOL_ASYNC_DATA_GBP_INDEP_PAGES_FOUND_IN_LBP'])))
        metric.append(dict(index_id="2500564", value=cs(row['POOL_ASYNC_INDEX_GBP_INDEP_PAGES_FOUND_IN_LBP'])))
        metric.append(dict(index_id="2500566", value=cs(row['POOL_ASYNC_XDA_GBP_INDEP_PAGES_FOUND_IN_LBP'])))
        metric.append(dict(index_id="2500568", value=cs(row['CACHING_TIER'])))
        metric.append(dict(index_id="2500570", value=cs(row['CACHING_TIER_IO_ERRORS'])))
        metric.append(dict(index_id="2500572", value=cs(row['POOL_DATA_CACHING_TIER_L_READS'])))
        metric.append(dict(index_id="2500574", value=cs(row['POOL_INDEX_CACHING_TIER_L_READS'])))
        metric.append(dict(index_id="2500576", value=cs(row['POOL_XDA_CACHING_TIER_L_READS'])))
        metric.append(dict(index_id="2500578", value=cs(row['POOL_COL_CACHING_TIER_L_READS'])))
        metric.append(dict(index_id="2500580", value=cs(row['POOL_DATA_CACHING_TIER_PAGE_WRITES'])))
        metric.append(dict(index_id="2500582", value=cs(row['POOL_INDEX_CACHING_TIER_PAGE_WRITES'])))
        metric.append(dict(index_id="2500584", value=cs(row['POOL_XDA_CACHING_TIER_PAGE_WRITES'])))
        metric.append(dict(index_id="2500586", value=cs(row['POOL_COL_CACHING_TIER_PAGE_WRITES'])))
        metric.append(dict(index_id="2500588", value=cs(row['POOL_DATA_CACHING_TIER_PAGE_UPDATES'])))
        metric.append(dict(index_id="2500590", value=cs(row['POOL_INDEX_CACHING_TIER_PAGE_UPDATES'])))
        metric.append(dict(index_id="2500592", value=cs(row['POOL_XDA_CACHING_TIER_PAGE_UPDATES'])))
        metric.append(dict(index_id="2500594", value=cs(row['POOL_COL_CACHING_TIER_PAGE_UPDATES'])))
        metric.append(dict(index_id="2500596", value=cs(row['POOL_CACHING_TIER_PAGE_READ_TIME'])))
        metric.append(dict(index_id="2500598", value=cs(row['POOL_CACHING_TIER_PAGE_WRITE_TIME'])))
        metric.append(dict(index_id="2500600", value=cs(row['POOL_DATA_CACHING_TIER_PAGES_FOUND'])))
        metric.append(dict(index_id="2500602", value=cs(row['POOL_INDEX_CACHING_TIER_PAGES_FOUND'])))
        metric.append(dict(index_id="2500604", value=cs(row['POOL_XDA_CACHING_TIER_PAGES_FOUND'])))
        metric.append(dict(index_id="2500606", value=cs(row['POOL_COL_CACHING_TIER_PAGES_FOUND'])))
        metric.append(dict(index_id="2500608", value=cs(row['POOL_DATA_CACHING_TIER_GBP_INVALID_PAGES'])))
        metric.append(dict(index_id="2500610", value=cs(row['POOL_INDEX_CACHING_TIER_GBP_INVALID_PAGES'])))
        metric.append(dict(index_id="2500612", value=cs(row['POOL_XDA_CACHING_TIER_GBP_INVALID_PAGES'])))
        metric.append(dict(index_id="2500614", value=cs(row['POOL_COL_CACHING_TIER_GBP_INVALID_PAGES'])))
        metric.append(dict(index_id="2500616", value=cs(row['POOL_DATA_CACHING_TIER_GBP_INDEP_PAGES_FOUND'])))
        metric.append(dict(index_id="2500618", value=cs(row['POOL_INDEX_CACHING_TIER_GBP_INDEP_PAGES_FOUND'])))
        metric.append(dict(index_id="2500620", value=cs(row['POOL_XDA_CACHING_TIER_GBP_INDEP_PAGES_FOUND'])))
        metric.append(dict(index_id="2500622", value=cs(row['POOL_COL_CACHING_TIER_GBP_INDEP_PAGES_FOUND'])))
        metric.append(dict(index_id="2500624", value=cs(row['POOL_ASYNC_DATA_CACHING_TIER_READS'])))
        metric.append(dict(index_id="2500626", value=cs(row['POOL_ASYNC_INDEX_CACHING_TIER_READS'])))
        metric.append(dict(index_id="2500628", value=cs(row['POOL_ASYNC_XDA_CACHING_TIER_READS'])))
        metric.append(dict(index_id="2500630", value=cs(row['POOL_ASYNC_COL_CACHING_TIER_READS'])))
        metric.append(dict(index_id="2500632", value=cs(row['POOL_ASYNC_DATA_CACHING_TIER_PAGE_WRITES'])))
        metric.append(dict(index_id="2500634", value=cs(row['POOL_ASYNC_INDEX_CACHING_TIER_PAGE_WRITES'])))
        metric.append(dict(index_id="2500636", value=cs(row['POOL_ASYNC_XDA_CACHING_TIER_PAGE_WRITES'])))
        metric.append(dict(index_id="2500638", value=cs(row['POOL_ASYNC_COL_CACHING_TIER_PAGE_WRITES'])))
        metric.append(dict(index_id="2500640", value=cs(row['POOL_ASYNC_DATA_CACHING_TIER_PAGE_UPDATES'])))
        metric.append(dict(index_id="2500642", value=cs(row['POOL_ASYNC_INDEX_CACHING_TIER_PAGE_UPDATES'])))
        metric.append(dict(index_id="2500644", value=cs(row['POOL_ASYNC_XDA_CACHING_TIER_PAGE_UPDATES'])))
        metric.append(dict(index_id="2500646", value=cs(row['POOL_ASYNC_COL_CACHING_TIER_PAGE_UPDATES'])))
        metric.append(dict(index_id="2500648", value=cs(row['POOL_ASYNC_DATA_CACHING_TIER_PAGES_FOUND'])))
        metric.append(dict(index_id="2500650", value=cs(row['POOL_ASYNC_INDEX_CACHING_TIER_PAGES_FOUND'])))
        metric.append(dict(index_id="2500652", value=cs(row['POOL_ASYNC_XDA_CACHING_TIER_PAGES_FOUND'])))
        metric.append(dict(index_id="2500654", value=cs(row['POOL_ASYNC_COL_CACHING_TIER_PAGES_FOUND'])))
        metric.append(dict(index_id="2500656", value=cs(row['POOL_ASYNC_DATA_CACHING_TIER_GBP_INVALID_PAGES'])))
        metric.append(dict(index_id="2500658", value=cs(row['POOL_ASYNC_INDEX_CACHING_TIER_GBP_INVALID_PAGES'])))
        metric.append(dict(index_id="2500660", value=cs(row['POOL_ASYNC_XDA_CACHING_TIER_GBP_INVALID_PAGES'])))
        metric.append(dict(index_id="2500662", value=cs(row['POOL_ASYNC_COL_CACHING_TIER_GBP_INVALID_PAGES'])))
        metric.append(dict(index_id="2500664", value=cs(row['POOL_ASYNC_DATA_CACHING_TIER_GBP_INDEP_PAGES_FOUND'])))
        metric.append(dict(index_id="2500666", value=cs(row['POOL_ASYNC_INDEX_CACHING_TIER_GBP_INDEP_PAGES_FOUND'])))
        metric.append(dict(index_id="2500668", value=cs(row['POOL_ASYNC_XDA_CACHING_TIER_GBP_INDEP_PAGES_FOUND'])))
        metric.append(dict(index_id="2500670", value=cs(row['POOL_ASYNC_COL_CACHING_TIER_GBP_INDEP_PAGES_FOUND'])))
        metric.append(dict(index_id="2500672", value=cs(row['ROWS_DELETED'])))
        metric.append(dict(index_id="2500674", value=cs(row['ROWS_INSERTED'])))
        metric.append(dict(index_id="2500676", value=cs(row['ROWS_UPDATED'])))
        metric.append(dict(index_id="2500678", value=cs(row['TOTAL_HASH_JOINS'])))
        metric.append(dict(index_id="2500680", value=cs(row['TOTAL_HASH_LOOPS'])))
        metric.append(dict(index_id="2500682", value=cs(row['HASH_JOIN_OVERFLOWS'])))
        metric.append(dict(index_id="2500684", value=cs(row['HASH_JOIN_SMALL_OVERFLOWS'])))
        metric.append(dict(index_id="2500686", value=cs(row['POST_SHRTHRESHOLD_HASH_JOINS'])))
        metric.append(dict(index_id="2500688", value=cs(row['TOTAL_OLAP_FUNCS'])))
        metric.append(dict(index_id="2500690", value=cs(row['OLAP_FUNC_OVERFLOWS'])))
        metric.append(dict(index_id="2500692", value=cs(row['DYNAMIC_SQL_STMTS'])))
        metric.append(dict(index_id="2500694", value=cs(row['STATIC_SQL_STMTS'])))
        metric.append(dict(index_id="2500696", value=cs(row['FAILED_SQL_STMTS'])))
        metric.append(dict(index_id="2500698", value=cs(row['SELECT_SQL_STMTS'])))
        metric.append(dict(index_id="2500700", value=cs(row['UID_SQL_STMTS'])))
        metric.append(dict(index_id="2500702", value=cs(row['DDL_SQL_STMTS'])))
        metric.append(dict(index_id="2500704", value=cs(row['MERGE_SQL_STMTS'])))
        metric.append(dict(index_id="2500706", value=cs(row['XQUERY_STMTS'])))
        metric.append(dict(index_id="2500708", value=cs(row['IMPLICIT_REBINDS'])))
        metric.append(dict(index_id="2500710", value=cs(row['BINDS_PRECOMPILES'])))
        metric.append(dict(index_id="2500712", value=cs(row['INT_ROWS_DELETED'])))
        metric.append(dict(index_id="2500714", value=cs(row['INT_ROWS_INSERTED'])))
        metric.append(dict(index_id="2500716", value=cs(row['INT_ROWS_UPDATED'])))
        metric.append(dict(index_id="2500718", value=cs(row['CALL_SQL_STMTS'])))
        metric.append(dict(index_id="2500720", value=cs(row['POOL_COL_L_READS'])))
        metric.append(dict(index_id="2500722", value=cs(row['POOL_TEMP_COL_L_READS'])))
        metric.append(dict(index_id="2500724", value=cs(row['POOL_COL_P_READS'])))
        metric.append(dict(index_id="2500726", value=cs(row['POOL_TEMP_COL_P_READS'])))
        metric.append(dict(index_id="2500728", value=cs(row['POOL_COL_LBP_PAGES_FOUND'])))
        metric.append(dict(index_id="2500730", value=cs(row['POOL_COL_WRITES'])))
        metric.append(dict(index_id="2500732", value=cs(row['POOL_ASYNC_COL_READS'])))
        metric.append(dict(index_id="2500734", value=cs(row['POOL_ASYNC_COL_READ_REQS'])))
        metric.append(dict(index_id="2500736", value=cs(row['POOL_ASYNC_COL_WRITES'])))
        metric.append(dict(index_id="2500738", value=cs(row['POOL_ASYNC_COL_LBP_PAGES_FOUND'])))
        metric.append(dict(index_id="2500740", value=cs(row['POOL_COL_GBP_L_READS'])))
        metric.append(dict(index_id="2500742", value=cs(row['POOL_COL_GBP_P_READS'])))
        metric.append(dict(index_id="2500744", value=cs(row['POOL_COL_GBP_INVALID_PAGES'])))
        metric.append(dict(index_id="2500746", value=cs(row['POOL_COL_GBP_INDEP_PAGES_FOUND_IN_LBP'])))
        metric.append(dict(index_id="2500748", value=cs(row['POOL_ASYNC_COL_GBP_L_READS'])))
        metric.append(dict(index_id="2500750", value=cs(row['POOL_ASYNC_COL_GBP_P_READS'])))
        metric.append(dict(index_id="2500752", value=cs(row['POOL_ASYNC_COL_GBP_INVALID_PAGES'])))
        metric.append(dict(index_id="2500754", value=cs(row['POOL_ASYNC_COL_GBP_INDEP_PAGES_FOUND_IN_LBP'])))
        metric.append(dict(index_id="2500756", value=cs(row['POOL_QUEUED_ASYNC_COL_REQS'])))
        metric.append(dict(index_id="2500758", value=cs(row['POOL_QUEUED_ASYNC_TEMP_COL_REQS'])))
        metric.append(dict(index_id="2500760", value=cs(row['POOL_QUEUED_ASYNC_COL_PAGES'])))
        metric.append(dict(index_id="2500762", value=cs(row['POOL_QUEUED_ASYNC_TEMP_COL_PAGES'])))
        metric.append(dict(index_id="2500764", value=cs(row['POOL_FAILED_ASYNC_COL_REQS'])))
        metric.append(dict(index_id="2500766", value=cs(row['POOL_FAILED_ASYNC_TEMP_COL_REQS'])))
        metric.append(dict(index_id="2500768", value=cs(row['SKIPPED_PREFETCH_COL_P_READS'])))
        metric.append(dict(index_id="2500770", value=cs(row['SKIPPED_PREFETCH_TEMP_COL_P_READS'])))
        metric.append(dict(index_id="2500772", value=cs(row['SKIPPED_PREFETCH_UOW_COL_P_READS'])))
        metric.append(dict(index_id="2500774", value=cs(row['SKIPPED_PREFETCH_UOW_TEMP_COL_P_READS'])))
        metric.append(dict(index_id="2500776", value=cs(row['TOTAL_COL_TIME'])))
        metric.append(dict(index_id="2500778", value=cs(row['TOTAL_COL_PROC_TIME'])))
        metric.append(dict(index_id="2500780", value=cs(row['TOTAL_COL_EXECUTIONS'])))
        metric.append(dict(index_id="2500782", value=cs(row['NUM_POOLED_AGENTS'])))
        metric.append(dict(index_id="2500784", value=cs(row['POST_THRESHOLD_HASH_JOINS'])))
        metric.append(dict(index_id="2500786", value=cs(row['PKG_CACHE_NUM_OVERFLOWS'])))
        metric.append(dict(index_id="2500788", value=cs(row['CAT_CACHE_OVERFLOWS'])))
        metric.append(dict(index_id="2500790", value=cs(row['TOTAL_ASYNC_RUNSTATS'])))
        metric.append(dict(index_id="2500792", value=cs(row['STATS_CACHE_SIZE'])))
        metric.append(dict(index_id="2500794", value=cs(row['TOTAL_HASH_GRPBYS'])))
        metric.append(dict(index_id="2500796", value=cs(row['HASH_GRPBY_OVERFLOWS'])))
        metric.append(dict(index_id="2500798", value=cs(row['POST_THRESHOLD_HASH_GRPBYS'])))
        metric.append(dict(index_id="2500800", value=cs(row['ACTIVE_HASH_GRPBYS'])))
        metric.append(dict(index_id="2500802", value=cs(row['SORT_HEAP_ALLOCATED'])))
        metric.append(dict(index_id="2500804", value=cs(row['SORT_SHRHEAP_ALLOCATED'])))
        metric.append(dict(index_id="2500806", value=cs(row['SORT_SHRHEAP_TOP'])))
        metric.append(dict(index_id="2500808", value=cs(row['POST_THRESHOLD_OLAP_FUNCS'])))
        metric.append(dict(index_id="2500810", value=cs(row['POST_THRESHOLD_COL_VECTOR_CONSUMERS'])))
        metric.append(dict(index_id="2500812", value=cs(row['TOTAL_COL_VECTOR_CONSUMERS'])))
        metric.append(dict(index_id="2500814", value=cs(row['ACTIVE_HASH_GRPBYS_TOP'])))
        metric.append(dict(index_id="2500816", value=cs(row['ACTIVE_HASH_JOINS_TOP'])))
        metric.append(dict(index_id="2500818", value=cs(row['ACTIVE_OLAP_FUNCS_TOP'])))
        metric.append(dict(index_id="2500820", value=cs(row['ACTIVE_PEAS'])))
        metric.append(dict(index_id="2500822", value=cs(row['ACTIVE_PEAS_TOP'])))
        metric.append(dict(index_id="2500824", value=cs(row['ACTIVE_PEDS'])))
        metric.append(dict(index_id="2500826", value=cs(row['ACTIVE_PEDS_TOP'])))
        metric.append(dict(index_id="2500828", value=cs(row['ACTIVE_SORT_CONSUMERS'])))
        metric.append(dict(index_id="2500830", value=cs(row['ACTIVE_SORT_CONSUMERS_TOP'])))
        metric.append(dict(index_id="2500832", value=cs(row['ACTIVE_SORTS_TOP'])))
        metric.append(dict(index_id="2500834", value=cs(row['ACTIVE_COL_VECTOR_CONSUMERS'])))
        metric.append(dict(index_id="2500836", value=cs(row['ACTIVE_COL_VECTOR_CONSUMERS_TOP'])))
        metric.append(dict(index_id="2500838", value=cs(row['SORT_CONSUMER_HEAP_TOP'])))
        metric.append(dict(index_id="2500840", value=cs(row['SORT_CONSUMER_SHRHEAP_TOP'])))
        metric.append(dict(index_id="2500842", value=cs(row['SORT_HEAP_TOP'])))
        metric.append(dict(index_id="2500844", value=cs(row['TOTAL_BACKUP_TIME'])))
        metric.append(dict(index_id="2500846", value=cs(row['TOTAL_BACKUP_PROC_TIME'])))
        metric.append(dict(index_id="2500848", value=cs(row['TOTAL_BACKUPS'])))
        metric.append(dict(index_id="2500850", value=cs(row['TOTAL_INDEX_BUILD_TIME'])))
        metric.append(dict(index_id="2500852", value=cs(row['TOTAL_INDEX_BUILD_PROC_TIME'])))
        metric.append(dict(index_id="2500854", value=cs(row['TOTAL_INDEXES_BUILT'])))
        metric.append(dict(index_id="2500856", value=cs(row['IDA_SEND_WAIT_TIME'])))
        metric.append(dict(index_id="2500858", value=cs(row['IDA_SENDS_TOTAL'])))
        metric.append(dict(index_id="2500860", value=cs(row['IDA_SEND_VOLUME'])))
        metric.append(dict(index_id="2500862", value=cs(row['IDA_RECV_WAIT_TIME'])))
        metric.append(dict(index_id="2500864", value=cs(row['IDA_RECVS_TOTAL'])))
        metric.append(dict(index_id="2500866", value=cs(row['IDA_RECV_VOLUME'])))
        metric.append(dict(index_id="2500868", value=cs(row['FCM_TQ_RECV_WAITS_TOTAL'])))
        metric.append(dict(index_id="2500870", value=cs(row['FCM_MESSAGE_RECV_WAITS_TOTAL'])))
        metric.append(dict(index_id="2500872", value=cs(row['FCM_TQ_SEND_WAITS_TOTAL'])))
        metric.append(dict(index_id="2500874", value=cs(row['FCM_MESSAGE_SEND_WAITS_TOTAL'])))
        metric.append(dict(index_id="2500876", value=cs(row['FCM_SEND_WAITS_TOTAL'])))
        metric.append(dict(index_id="2500878", value=cs(row['FCM_RECV_WAITS_TOTAL'])))
        metric.append(dict(index_id="2500880", value=cs(row.get('EXT_TABLE_RECV_WAIT_TIME', 0))))
        metric.append(dict(index_id="2500882", value=cs(row.get('EXT_TABLE_RECVS_TOTAL', 0))))
        metric.append(dict(index_id="2500884", value=cs(row.get('EXT_TABLE_RECV_VOLUME', 0))))
        metric.append(dict(index_id="2500886", value=cs(row.get('EXT_TABLE_READ_VOLUME', 0))))
        metric.append(dict(index_id="2500888", value=cs(row.get('EXT_TABLE_SEND_WAIT_TIME', 0))))
        metric.append(dict(index_id="2500890", value=cs(row.get('EXT_TABLE_SENDS_TOTAL', 0))))
        metric.append(dict(index_id="2500892", value=cs(row.get('EXT_TABLE_SEND_VOLUME', 0))))
        metric.append(dict(index_id="2500894", value=cs(row.get('EXT_TABLE_WRITE_VOLUME', 0))))
        metric.append(dict(index_id="2500896", value=cs(row.get('COL_VECTOR_CONSUMER_OVERFLOWS', 0))))
        metric.append(dict(index_id="2500898", value=cs(row.get('TOTAL_COL_SYNOPSIS_TIME', 0))))
        metric.append(dict(index_id="2500900", value=cs(row.get('TOTAL_COL_SYNOPSIS_PROC_TIME', 0))))
        metric.append(dict(index_id="2500902", value=cs(row.get('TOTAL_COL_SYNOPSIS_EXECUTIONS', 0))))
        metric.append(dict(index_id="2500904", value=cs(row.get('COL_SYNOPSIS_ROWS_INSERTED', 0))))
        metric.append(dict(index_id="2500906", value=cs(row.get('LOB_PREFETCH_WAIT_TIME', 0))))
        metric.append(dict(index_id="2500908", value=cs(row.get('LOB_PREFETCH_REQS', 0))))
        metric.append(dict(index_id="2500910", value=cs(row.get('FED_ROWS_DELETED', 0))))
        metric.append(dict(index_id="2500912", value=cs(row.get('FED_ROWS_INSERTED', 0))))
        metric.append(dict(index_id="2500914", value=cs(row.get('FED_ROWS_UPDATED', 0))))
        metric.append(dict(index_id="2500916", value=cs(row.get('FED_ROWS_READ', 0))))
        metric.append(dict(index_id="2500918", value=cs(row.get('FED_WAIT_TIME', 0))))
        metric.append(dict(index_id="2500920", value=cs(row.get('FED_WAITS_TOTAL', 0))))
        metric.append(dict(index_id="2500922", value=cs(row.get('APPL_SECTION_INSERTS', 0))))
        metric.append(dict(index_id="2500924", value=cs(row.get('APPL_SECTION_LOOKUPS', 0))))
        metric.append(dict(index_id="2500926", value=cs(row.get('SHR_WORKSPACE_ACTIVE', 0))))
        metric.append(dict(index_id="2500928", value=cs(row.get('SHR_WORKSPACE_INACTIVE', 0))))
        metric.append(dict(index_id="2500930", value=cs(row.get('ADM_OVERFLOWS', 0))))
        metric.append(dict(index_id="2500932", value=cs(row.get('ADM_BYPASS_ACT_TOTAL', 0))))
    # 获取max_connections
    sql3 = "SELECT value FROM sysibmadm.dbmcfg WHERE name = 'max_connections';"
    rs3 = DBUtil.getValue(db2, sql3)
    max_connections = -1
    if rs3:
        for row in rs3:
            max_connections = row['VALUE']
    conn_used = 0
    if max_connections == '-1':
        conn_used = 0
    else:
        conn_used = round(int(cur_conns) / int(max_connections) * 100, 2)
    metric.append(dict(index_id="2500934", value=str(conn_used)))


if __name__ == "__main__":
    metric = []
    cur_time = datetime.now()
    db2 = DBUtil.get_db2_env(exflag=3)
    metric.append(dict(index_id="1000102", value=str(round((datetime.now() - cur_time).microseconds / 1024, 0))))
    rs = []
    if db2.conn:
        metric.append(dict(index_id="2500000", value="连接成功"))
        get_db2_health(db2, metric)
    else:
        metric.append(dict(index_id="2500000", value="连接失败"))
    lat_time = datetime.now()
    diff_ms = (lat_time - cur_time).microseconds
    metric.append(dict(index_id="1000101", value=str(round(diff_ms / 1024, 0))))
    print('{"results":' + json.dumps(metric, ensure_ascii=False) + '}')
