#
#Fri Jul 06 17:47:32 CST 2018
jsp=http\://127.0.0.1\:18081/DBAIOps/jsp/pages/nobrowserpages/chartsByNoBrowser.jsp
monthjs=echartsToImgByMonth.js
weekjs=echartsToImgByWeek.js
dayjs=echartsToImgByDay.js
autoreport=0 0 5 1/1 * ?
monthreportimg=true
